spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console.enabled: true

fractions-csv-configuration:
  month-position: 0
  profile-id-position: 1
  ratio-position: 2
  first-row-title: true
  delimiter: ","

meter-reading-csv-configuration:
  meter-id-position: 0
  profile-id-position: 1
  month-position: 2
  meter-reading-position: 3
  first-row-title: true
  delimiter: ","

month-csv-configuration:
  january: "JAN"
  february: "FEB"
  march: "MAR"
  april: "APR"
  may: "MAY"
  june: "JUN"
  july: "JUL"
  august: "AUG"
  september: "SEP"
  october: "OCT"
  november: "NOV"
  december: "DEC"
